---
name: sap_deployment_automation_framework
description: |
  Executes SDAF deployment process
schedule:
  - boot/boot_to_desktop
  - sles4sap/sap_deployment_automation_framework/create_deployer_vm
  - sles4sap/sap_deployment_automation_framework/connect_to_deployer
  - sles4sap/sap_deployment_automation_framework/configure_deployer
  - sles4sap/sap_deployment_automation_framework/deploy_workload_zone
  - sles4sap/sap_deployment_automation_framework/deploy_sap_systems
  - sles4sap/sap_deployment_automation_framework/execute_ansible_playbooks
