# SUSE's openQA tests
#
# Copyright SUSE LLC
# SPDX-License-Identifier: FSFAP
# Maintainer: QE-SAP <qe-sap@suse.de>

package sles4sap::sap_deployment_automation_framework::configure_sap_systems_tfvars;

use strict;
use warnings;
use testapi;
use Exporter qw(import);
use Carp qw(croak);
use utils qw(write_sut_file);
use sles4sap::sap_deployment_automation_framework::deployment qw(get_os_variable);
use sles4sap::sap_deployment_automation_framework::configure_workload_tfvars qw(compile_tfvars_section);

=head1 SYNOPSIS

Library with common functions for Microsoft SDAF deployment automation that help with preparation of tfvars file.

=cut

our @EXPORT = qw(
  create_sap_systems_tfvars
  validate_components
);


=head2 validate_components

    validate_components(components=>['db_install', 'db_ha']);

Checks if components list is valid and supported by code. Croaks if not.
Currently supported components are:

=over

=item * B<components>: B<ARRAYREF> of components that should be installed.
    Supported values:
        db_install : Basic DB installation
        db_ha : Database HA setup
        nw_pas : Installs primary application server (PAS)
        nw_aas : Installs additional application server (AAS)
        nw_ensa : Installs enqueue replication server (ERS)

=back

=cut

sub validate_components {
    my (%args) = @_;
    croak '$args{components} must be an ARRAYREF' unless ref($args{components}) eq 'ARRAY';

    my %valid_components = ('db_install' => 'Basic DB installation.',
        db_ha => 'db_ha : Database HA setup',
        nw_pas => 'db_pas : Installs primary application server (PAS)',
        nw_aas => 'nw_aas : Installs additional application server (AAS)',
        nw_ensa => 'nw_ensa : Installs enqueue replication server (ERS)');

    for my $component (@{$args{components}}) {
        croak "Unsupported component: '$component'\nSupported values:\n" . join("\n", values(%valid_components))
          unless grep /^$component$/, keys(%valid_components);
    }
    # need to return positive value for unit test to work properly
    return 1;
}

=head2 create_sap_systems_tfvars

    create_sap_systems_tfvars(components=>['db_install', 'db_ha']);



=over

=item * B<environment>: SDAF environment. Can be supplied using OpenQA setting 'SDAF_ENV_CODE'

=item * B<location>: Public cloud location. Can be supplied using OpenQA setting 'PUBLIC_CLOUD_REGION'

=item * B<components>: B<ARRAYREF> of components that should be installed.
    Supported values:
        db_install : Basic DB installation
        db_ha : Database HA setup
        nw_pas : Installs primary application server (PAS)
        nw_aas : Installs additional application server (AAS)
        nw_ensa : Installs enqueue replication server (ERS)

=back

=cut

sub create_sap_systems_tfvars {
    my (%args) = @_;


    for my $arg ('job_id', 'network_data', 'workload_vnet_code') {
        croak("Missing mandatory argument \$args{$arg}") unless $args{$arg};
    }

    my %tfvars_data;
    $tfvars_data{file_header} = "### File was generated by OpenQA automation according to template:\n### https://github.com/Azure/SAP-automation-samples/blob/main/Terraform/WORKSPACES/SYSTEM/LAB-SECE-SAP04-L00/LAB-SECE-SAP04-L00.tfvars\n";

    my $tfvars_file = get_os_variable('workload_zone_parameter_file');
    write_sap_systems_tfvars_file(tfvars_data => \%tfvars_data, tfvars_file => $tfvars_file);
    upload_logs($tfvars_file, log_name => 'workload_zone.tfvars.txt');
}

=head2 write_sap_systems_tfvars_file

    write_sap_systems_tfvars_file();

=cut

sub write_sap_systems_tfvars_file {
    my (%args) = @_;
    for my $arg ('tfvars_data', 'tfvars_file') {
        croak "Missing mandatory argument \$args{$arg}" unless $args{$arg};
    }
    croak 'Argument \$args{tfvars_data} must be a HASHREF' unless ref($args{tfvars_data});

    my $file_contents = $args{tfvars_data}->{file_header};
    $file_contents .= compile_tfvars_section($args{tfvars_data}->{env_definitions});
    $file_contents .= compile_tfvars_section($args{tfvars_data}->{sap_systems_networking});
    $file_contents .= compile_tfvars_section($args{tfvars_data}->{cluster_settings});
    $file_contents .= compile_tfvars_section($args{tfvars_data}->{database_tiers});
    $file_contents .= compile_tfvars_section($args{tfvars_data}->{application_tier});
    $file_contents .= compile_tfvars_section($args{tfvars_data}->{sap_central_services});
    $file_contents .= compile_tfvars_section($args{tfvars_data}->{application_servers});
    $file_contents .= compile_tfvars_section($args{tfvars_data}->{web_dispatchers});
    $file_contents .= compile_tfvars_section($args{tfvars_data}->{miscellanous_settings});
    $file_contents .= compile_tfvars_section($args{tfvars_data}->{nfs_support});
    write_sut_file($args{tfvars_file}, $file_contents);
}

=head2 define_workload_environment

    define_workload_environment();

Returns tfvars environment definitions section in hash format.
Example: {environment : 'LAB', location : 'swedencentral'}

=over

=item * B<environment>: SDAF environment

=item * B<location>: Public cloud location

=back

=cut

sub define_workload_environment {
    my (%args) = @_;
    for my $arg ('environment', 'location') {
        croak "Missing mandatory argument \$args{$arg}" unless $args{$arg};
    }
    my %result = (
        header => '### Environment definitions ###',
        custom_disk_sizes_filename => '"custom_sizes.json"',
        environment => "\"$args{environment}\"",
        location => "\"$args{location}\"",
        # upgrade_packages defines if all packages should be upgraded after installation
        upgrade_packages => 'true',
        tags => '{"DeployedBy" = "OpenQA-SDAF-automation"}'
    );
    return (\%result);
}

=head2 define_networking

    define_networking();

Returns tfvars environment definitions section in hash format.
Example: {environment : 'LAB', location : 'swedencentral'}

=cut

sub define_networking {
    my (%args) = @_;
    croak 'Missing mandatory argument $args{workload_vnet_code}' unless $args{workload_vnet_code};
    my %result = (
        header => '### Environment definitions ###',
        # The network logical name is mandatory - it is used in the naming convention and should map to the workload virtual network logical name
        network_logical_name => "\"$args{workload_vnet_code}\"",
        # use_loadbalancers_for_standalone_deployments is a boolean flag that can be used to control if standalone deployments (non HA) will have load balancers
        use_loadbalancers_for_standalone_deployments => 'false',
        # use_private_endpoint is a boolean flag controlling if the key vaults and storage accounts have private endpoints
        use_private_endpoint => 'true'
    );
    return (\%result);
}


=head2 define_cluster_settings

    define_cluster_settings();

=cut

sub define_cluster_settings {
    my (%args) = @_;
    croak 'Missing mandatory argument $args{fencing_type}' unless $args{fencing_type};
    my %result = (
        header => '### Environment definitions ###',
        # scs_cluster_type defines cluster quorum type; AFA (Azure Fencing Agent), ASD (Azure Shared Disk), ISCSI
        scs_cluster_type => "\"$args{fencing_type}\"",
        # database_cluster_type defines cluster quorum type; AFA (Azure Fencing Agent), ASD (Azure Shared Disk), ISCSI
        database_cluster_type => "\"$args{fencing_type}\"",
        # use_msi_for_clusters if defined will use managed service identity for the Pacemaker cluster fencing
        use_msi_for_clusters => 'false',
        # use_simple_mount specifies if Simple mounts are used (Applicable for SLES 15 SP# or newer)
        use_simple_mount => 'true'
    );
    return (\%result);
}

=head2 define_database_tier

    define_database_tier();

=cut

sub define_database_tier {
    my (%args) = @_;
    for my $arg ('environment', 'location') {
        croak "Missing mandatory argument \$args{$arg}" unless $args{$arg};
    }
    my %result = (
        header => '### Environment definitions ###',

    );
    return (\%result);
}