# SUSE's openQA tests
#
# Copyright SUSE LLC
# SPDX-License-Identifier: FSFAP
# Maintainer: QE-SAP <qe-sap@suse.de>

package sles4sap::sap_deployment_automation_framework::configure_workload_tfvars;

use strict;
use warnings;
use testapi;
use Exporter qw(import);
use Carp qw(croak);
use utils qw(write_sut_file);
use sles4sap::sap_deployment_automation_framework::deployment qw(get_os_variable);
use sles4sap::sap_deployment_automation_framework::naming_conventions qw(convert_region_to_short);
use sles4sap::sap_deployment_automation_framework::deployment_connector qw(find_deployment_id);

=head1 SYNOPSIS

Library with common functions for Microsoft SDAF deployment automation that help with preparation of tfvars file.

=cut

our @EXPORT = qw(
  create_workload_tfvars
  compile_tfvars_section
);

=head2 create_workload_tfvars

    create_workload_tfvars(components=>['db_install', 'db_ha']);



=over

=item * B<environment>: SDAF environment. Can be supplied using OpenQA setting 'SDAF_ENV_CODE'

=item * B<location>: Public cloud location. Can be supplied using OpenQA setting 'PUBLIC_CLOUD_REGION'

=item * B<components>: B<ARRAYREF> of components that should be installed.
    Supported values:
        db_install : Basic DB installation
        db_ha : Database HA setup
        nw_pas : Installs primary application server (PAS)
        nw_aas : Installs additional application server (AAS)
        nw_ensa : Installs enqueue replication server (ERS)

=back

=cut

sub create_workload_tfvars {
    my (%args) = @_;
    $args{environment} //= get_required_var('SDAF_ENV_CODE');
    $args{location} //= get_required_var('PUBLIC_CLOUD_REGION');
    $args{resource_group} //= get_required_var('SDAF_RESOURCE_GROUP');
    $args{job_id} //= find_deployment_id();

    for my $arg ('job_id', 'network_data', 'workload_vnet_code') {
        croak("Missing mandatory argument \$args{$arg}") unless $args{$arg};
    }

    my %tfvars_data;
    $tfvars_data{file_header} = "### File was generated by OpenQA automation according to template:\n### https://github.com/Azure/SAP-automation-samples/blob/main/Terraform/WORKSPACES/SYSTEM/LAB-SECE-SAP04-L00/LAB-SECE-SAP04-L00.tfvars\n";
    $tfvars_data{env_definitions} = define_workload_environment(
        environment => $args{environment}, location => $args{location}, resource_group => $args{resource_group});
    $tfvars_data{workload_networking} = define_networking(
        environment => $args{environment},
        location => $args{location},
        job_id => $args{job_id},
        workload_vnet_code => $args{workload_vnet_code}
    );
    $tfvars_data{subnet_definition} = define_subnets(network_data => $args{network_data});
    $tfvars_data{nat_configuration} = define_nat_section(
        environment => $args{environment},
        sdaf_region => convert_region_to_short($args{location}),
        workload_vnet_code => $args{workload_vnet_code});
    $tfvars_data{iscsi_devices} = define_iscsi_devices();
    $tfvars_data{storage_account} = define_storage_account();
    my $tfvars_file = get_os_variable('workload_zone_parameter_file');

    write_workload_tfvars_file(tfvars_data => \%tfvars_data, tfvars_file => $tfvars_file);
    upload_logs($tfvars_file, log_name => 'workload_zone.tfvars.txt');
}

=head2 write_workload_tfvars_file

    write_workload_tfvars_file();

Writes $args{tfvars_data} into target tfvars file located on SUT.
$args{tfvars_data} is a HASHREF containg individual sections that should be included in final tfvars content.
Example:
{
file_header => "Comment placed on top of the tfvars file",
env_definitions => {header => 'Comment placed on top of a section',
    tfvars_variable = 'value', tfvars_variable_2 = 'value2'},
workload_networking => {header => 'Comment placed on top of a section',
    tfvars_variable_3 = 'value3', tfvars_variable_4 = 'value4'},
}

=over

=item * B<tfvars_file>: Target tfvars file location

=item * B<tfvars_data>: Target tfvars file data - Must be a HASHREF

=back

=cut

sub write_workload_tfvars_file {
    my (%args) = @_;
    for my $arg ('tfvars_data', 'tfvars_file') {
        croak "Missing mandatory argument \$args{$arg}" unless $args{$arg};
    }
    croak 'Argument \$args{tfvars_data} must be a HASHREF' unless ref($args{tfvars_data});

    my $file_contents = $args{tfvars_data}->{file_header};
    $file_contents .= compile_tfvars_section($args{tfvars_data}->{env_definitions});
    $file_contents .= compile_tfvars_section($args{tfvars_data}->{workload_networking});
    $file_contents .= compile_tfvars_section($args{tfvars_data}->{subnet_definition});
    $file_contents .= compile_tfvars_section($args{tfvars_data}->{nat_configuration});
    $file_contents .= compile_tfvars_section($args{tfvars_data}->{iscsi_devices});
    $file_contents .= compile_tfvars_section($args{tfvars_data}->{storage_account});
    write_sut_file($args{tfvars_file}, $file_contents);
}

=head2 compile_tfvars_section

    compile_tfvars_section($section_data);

=over

=item * B<$section_data>:

=back

=cut

sub compile_tfvars_section {
    my ($section_data) = @_;
    my $header = $section_data->{header};
    delete $section_data->{header};
    return (join("\n", "\n\n$header", map { "$_ = $section_data->{$_}" } keys(%{$section_data})));
}

=head2 define_workload_environment

    define_workload_environment();

Returns tfvars environment definitions section in hash format.
Example: {environment : 'LAB', location : 'swedencentral'}

=over

=item * B<environment>: SDAF environment

=item * B<location>: Public cloud location

=back

=cut

sub define_workload_environment {
    my (%args) = @_;
    for my $arg ('environment', 'location') {
        croak "Missing mandatory argument \$args{$arg}" unless $args{$arg};
    }
    my %result = (
        header => '### Environment definitions ###',
        resource_group => "\"$args{resource_group}\"",
        environment => "\"$args{environment}\"",
        location => "\"$args{location}\"",
        automation_username => '"' . get_var('PUBLIC_CLOUD_USER', 'azureadm') . '"',
        # enable_rbac_authorization_for_keyvault Controls the access policy model for the workload zone keyvault.
        enable_rbac_authorization_for_keyvault => 'false',
        # enable_purge_control_for_keyvaults is an optional parameter that can be used to disable the purge protection fro Azure keyvaults
        enable_purge_control_for_keyvaults => 'false',
        # use_spn defines if the deployments are performed using Service Principals or the deployer's managed identiry, true=SPN, false=MSI
        use_spn => 'true',
        # Defines the number of workload _vms to create
        utility_vm_count => '0',
        # These tags will be applied to all resources
        tags => '{"DeployedBy" = "OpenQA-SDAF-automation"}'
    );

    return (\%result);
}

=head2 define_networking

    define_networking();

Returns tfvars environment definitions section in hash format.
Example: {environment : 'LAB', location : 'swedencentral'}

=over

=item * B<environment>: SDAF environment

=item * B<location>: Public cloud location

=item * B<job_id>: OpenQA job ID which the deployment belongs to

=item * B<network_address_space>: Network address space reserved for all subnets

=back

=cut

sub define_networking {
    my (%args) = @_;
    for my $arg ('environment', 'location', 'job_id', 'workload_vnet_code') {
        croak "Missing mandatory argument \$args{$arg}" unless $args{$arg};
    }
    my %result = (
        header => '### Networking ###',
        # The network logical name is mandatory - it is used in the naming convention and should map to the workload virtual network logical name
        network_logical_name => "$args{workload_vnet_code}",
        # Workload VNET name - keep as short as possible as resource naming has limitations
        network_name => "\"OpenQA-$args{job_id}\"",
        # disable private endpoints for key vaults and storage accounts
        use_private_endpoint => 'false',
        # disable service endpoints for key vaults and storage accounts
        use_service_endpoint => 'true',
        # Peering between control plane and workload zone (enable connection from deployer VM to SUT network)
        peer_with_control_plane_vnet => 'true',
        # Enables firewall for keyvaults and storage - only SUT subnets will be able to access it
        enable_firewall_for_keyvaults_and_storage => 'true',
        # Disable resource delete lock for cleanup to work properly
        place_delete_lock_on_resources => 'false',
        # Defines if a custom dns solution is used
        use_custom_dns_a_registration => 'false',
        # Defines if the Virtual network for the Virtual machines is registered with DNS
        # This also controls the creation of DNS entries for the load balancers
        register_virtual_network_to_dns => 'true',
        # Boolean value indicating if storage accounts and key vaults should be registered to the corresponding dns zones
        register_storage_accounts_keyvaults_with_dns => 'false'
    );
    return \%result;
}

=head2 define_nat_section

    define_nat_section();

Returns tfvars environment definitions section in hash format.
Example: {environment : 'LAB', location : 'swedencentral'}

=over

=item * B<environment>: SDAF environment

=item * B<sdaf_region>: Public cloud location

=item * B<deployer_vnet_code>: Public cloud location

=back

=cut

sub define_nat_section {
    my (%args) = @_;
    for my $arg ('environment', 'sdaf_region', 'workload_vnet_code') {
        croak "Missing mandatory argument \$args{$arg}" unless $args{$arg};
    }
    my %result = (
        header => '###  NAT Configuration ###',
        deploy_nat_gateway => 'true',
        nat_gateway_name => "\"$args{environment}-$args{sdaf_region}-$args{workload_vnet_code}-NG_0001\"",
        nat_gateway_public_ip_tags => '{"ipTagType": "OpenQA-SDAF-automation", "tag": "OpenQA-SDAF-automation"}'
    );

    return (\%result);
}

=head2 define_subnets

    define_subnets();

Returns tfvars environment definitions section in hash format.
Example: {environment : 'LAB', location : 'swedencentral'}

=over

=item * B<environment>: SDAF environment

=item * B<location>: Public cloud location

=back

=cut

sub define_subnets {
    my (%args) = @_;
    croak 'Missing mandatory argument $args{network_data}' unless $args{network_data};
    my %result = (
        header => '###  Subnet definitions ###',
        network_address_space => "\"$args{network_data}->{network_address_space}\"",
        iscsi_subnet_address_prefix => "\"$args{network_data}->{iscsi_subnet_address_prefix}\"",
        web_subnet_address_prefix => "\"$args{network_data}->{web_subnet_address_prefix}\"",
        admin_subnet_address_prefix => "\"$args{network_data}->{admin_subnet_address_prefix}\"",
        db_subnet_address_prefix => "\"$args{network_data}->{db_subnet_address_prefix}\"",
        app_subnet_address_prefix => "\"$args{network_data}->{app_subnet_address_prefix}\""
    );

    return (\%result);
}

=head2 define_iscsi_devices

    define_iscsi_devices();

Returns tfvars environment definitions section in hash format.
Example: {environment : 'LAB', location : 'swedencentral'}

=cut

sub define_iscsi_devices {
    # Fencing mechanism AFA (Azure fencing agent - MSI), ASD (Azure shared disk - SBD), ISCSI (iSCSI based SBD fencing)
    # Default value: 'msi' - AFA - Azure fencing agent (MSI)
    my $fencing_type = get_var('SDAF_FENCING_MECHANISM', 'msi');

    # Ensures consistent OpenQA setting names across all types deployment solutions.
    # msi = MSI based fencing
    # sbd = iSCSI based SBD devices
    # asd = Azure shared disk as SBD device
    my %supported_fencing_values = (msi => 'AFA', sbd => 'ISCSI', asd => 'ASD');
    die "Fencing type '$fencing_type' is not supported" unless grep /^$fencing_type$/, keys(%supported_fencing_values);

    my %result = (header => '###  ISCSI Devices ###');
    if ($fencing_type eq 'sbd') {
        # Number of iSCSI devices to be created
        $result{iscsi_count} = '"' . get_var('SDAF_ISCSI_DEVICE_COUNT', 3) . '"';
        # Size of iSCSI Virtual Machines to be created
        $result{iscsi_size} = '"Standard_D2s_v3"';
        # Defines if the iSCSI devices use DHCP
        $result{iscsi_useDHCP} = 'true';
        # Defines the Virtual Machine authentication type for the iSCSI device
        $result{iscsi_authentication_type} = '"key"';
        # Defines the username for the iSCSI devices
        $result{iscsi_authentication_username} = '"azureadm"';
        # Defines the Availability zones for the iSCSI devices
        $result{iscsi_vm_zones} = '["1", "2", "3"]';
    }
    else {
        # Do not deploy ISCSI if not needed
        $result{iscsi_count} = '"0"';
    }
    return (\%result);
}


=head2 define_storage_account

    define_storage_account();

Returns tfvars environment definitions section in hash format.
Example: {environment : 'LAB', location : 'swedencentral'}

=cut

sub define_storage_account {
    my %result = (
        header => '###  Storage account details ###',
        # Defines the size of the install volume
        install_volume_size => '1024',
        # NFS will be provided using 'Azure filesystem' (AFS). NFS is used for serving installation media to SUT.
        NFS_provider => 'AFS',
        # Create separate storage for transport. Not needed for our testing
        create_transport_storage => 'false'
    );

    return (\%result);
}
